name: ubuntu_build

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  ubuntu_build:
    name: "${{ matrix.python-version }}"
    runs-on: "${{ matrix.os }}"

    timeout-minutes: 60

    strategy:
      fail-fast: false
      
      matrix:
        os: 
          - "ubuntu-latest"
        python-version:
          # - "3.11-dev"
          - "3.12-dev"
          # - "3.11"
          # - "3.12"
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
          #git clone https://github.com/pyenv/pyenv
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential pkg-config ccache gdb lcov libb2-dev libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev libzstd-dev lzma lzma-dev strace tk-dev uuid-dev xvfb zlib1g-dev
          version: 1.0
      - run: pwd
      - run: |
          set -xe
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
          $PYENV_ROOT/bin/pyenv --debug install ${{ matrix.python-version }} -v
          #$PYENV_ROOT/bin/pyenv global ${{ matrix.python-version }}
          #$PYENV_ROOT/bin/pyenv rehash
          # echo $PYENV_ROOT
          # echo "$PYENV_ROOT/shims:$PYENV_ROOT/bin" >> $GITHUB_PATH
          # $PYENV_ROOT/bin/pyenv --debug install ${{ matrix.python-version }}
          sudo ln -sf $PYENV_ROOT/versions/3.12-dev/bin/python3 /usr/local/bin/python

          # $PYENV_ROOT/bin/pyenv global ${{ matrix.python-version }}
          # $PYENV_ROOT/bin/pyenv rehash
      - run: |
          export PYENV_ROOT="$HOME/.pyenv"
          ls -lR $PYENV_ROOT/versions
          ls -lR /usr/local/bin/python
      - run: python --version
      - run: python -m pip --version
      - shell: python  # Prove that actual Python == expected Python
        env:
          EXPECTED_PYTHON: ${{ matrix.python-version }}
        run: import os, sys ; print(sys.version)
      - run: python -m pip install tox
      - run: python -m tox -v -- -rfsEX
