name: ubuntu_build
on:
  workflow_dispatch:

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  ubuntu_build:
    strategy:
      fail-fast: False
      matrix:
        python-version:
          # - "3.11-dev"
          - "3.12-dev"
          # - "3.11"
          # - "3.12"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git clone https://github.com/pyenv/pyenv
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential pkg-config ccache gdb lcov libb2-dev libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev libzstd-dev lzma lzma-dev strace tk-dev uuid-dev xvfb zlib1g-dev
          version: 1.0

      # https://github.com/pyenv/pyenv#installation
      
      - name: "Install system dependencies"
        run: |
          echo BEFORE
          cat /etc/apt/sources.list.d/ubuntu.sources
          # https://wbk.one/article/42a272c3/apt-get-build-dep-to-install-build-deps
          sudo sed -i.bak 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          echo AFTER
          cat /etc/apt/sources.list.d/ubuntu.sources
          sudo apt-get update
          #sudo apt-get install -y libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev libffi-dev
          sudo apt-get build-dep -y python3
      - run: pwd
      - env:
          PYENV_ROOT: ./pyenv
        run: |
          echo $PYENV_ROOT
          echo "$PYENV_ROOT/shims:$PYENV_ROOT/bin" >> $GITHUB_PATH
          $PYENV_ROOT/bin/pyenv --debug install ${{ matrix.python-version }}
          sudo ln -sf $PYENV_ROOT/versions/$PYVER/bin/python3 /usr/local/bin/python

          $PYENV_ROOT/bin/pyenv global ${{ matrix.python-version }}
          $PYENV_ROOT/bin/pyenv rehash
      - run: python --version
      - run: python -m pip --version
      - shell: python  # Prove that actual Python == expected Python
        env:
          EXPECTED_PYTHON: ${{ matrix.python-version }}
        run: import os, sys ; print(sys.version)
      - run: python -m pip install tox
      - run: python -m tox -v -- -rfsEX
