name: ubuntu_build
on:
  workflow_dispatch:

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  ubuntu_build:
    strategy:
      fail-fast: False
      matrix:
        python-version:
          - "3.11-dev"
          - "3.12-dev"
          - "3.11"
          - "3.12"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git clone https://github.com/pyenv/pyenv
          # sudo apt-get update -q; sudo apt install -yq make build-essential libssl-dev zlib1g-dev \
          # libbz2-dev libreadline-dev libsqlite3-dev curl \
          # libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
          sudo apt-get update -q;
          # original from coverage.py:
          sudo apt-get build-essential pkg-config ccache gdb lcov libb2-dev libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev libzstd-dev lzma lzma-dev strace tk-dev uuid-dev xvfb zlib1g-dev
      # https://github.com/pyenv/pyenv#installation
      - run: pwd
      - env:
          PYENV_ROOT: ./pyenv
        run: |
          echo $PYENV_ROOT
          echo "$PYENV_ROOT/shims:$PYENV_ROOT/bin" >> $GITHUB_PATH
          $PYENV_ROOT/bin/pyenv --debug install ${{ matrix.python-version }}
          $PYENV_ROOT/bin/pyenv global ${{ matrix.python-version }}
          $PYENV_ROOT/bin/pyenv rehash
      - run: python --version
      - run: python -m pip --version
      - shell: python  # Prove that actual Python == expected Python
        env:
          EXPECTED_PYTHON: ${{ matrix.python-version }}
        run: import os, sys ; print(sys.version)
      - run: python -m pip install tox
      - run: python -m tox -v -- -rfsEX
